# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: default commands
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  new:
    desc: setup new article
    deps: [default]
    cmds:
      - npx zenn new:article
    silent: true
  preview:
    desc: start preview server
    deps: [default]
    cmds:
      - npx zenn preview
